<label>รหัสผู้ปวย</label> <?=$data->p_id?> <br/>
<label>สิทธิการรักษา</label> <?=$data->pv_id?> <br/>
<label>ชื่อ - สกุล</label> <?=$data->p_name?> <?=$data->p_surname?> <br/>
<label>เลขบัตรประชาชน</label> <?=$data->p_nid?> <br/>
<label>วัน/เดือน/ปีเกิด</label> <?=$data->p_birthday?> <br/>
<label>อายุ</label> <?=$data->p_age?> <br/>
<label>เพศ</label> <?=$data->p_sex?> <br/>
<label >สัญชาติ</label> <?=$data->p_national?> <br/>
<label>สถานภาพ</label> <?=$data->p_status?> <br/>
<label >ที่อยู่</label> <?=$data->p_address?> <br/>
<label>เบอร์โทรศัพท์</label> <?=$data->p_tel?> <br/>
<label >น้ำหนัก</label> <?=$data->p_wieght?> <br/>
<label>ส่วนสูง</label> <?=$data->p_hight?> <br/>
<label >โรคประจำตัว</label> <?=$data->disease?>  <br/>
<label>กรุ๊ปเลือด</label> <?=$data->blood?> <br/>
<label >แพ้ยา</label> <?=$data->allergic?> <br/>
<label>ผู้ที่ติดต่อในกรณีฉุกเฉิน</label> <?=$data->delegate?> <br/>
<label >เบอร์โทรผู้ติดต่อ</label> <?=$data->delegate_tel?> <br/>
<label>ความสัมพันธ์</label> <?=$data->relationship?> <br/>
